# Generated by Django 4.0.4 on 2022-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_orderitems_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
