# Generated by Django 4.0.4 on 2022-04-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='orderded',
            new_name='ordered',
        ),
    ]
