# Generated by Django 4.0.4 on 2022-05-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_villeshipping_alter_orderitems_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
